### ISSUE TITLE
Move destructive tests from status-go to status-scale

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-scale#12]
IMO the only one test worth moving is the test for half-opened sockets and lost messages due to read deadline.

https://github.com/status-im/status-go/blob/develop/t/destructive/peers_test.go#L62

Should be quite straightforward to move

**Comment by adriacidre** [comment]
The original test ([TestSentEnvelope](https://github.com/status-im/status-go/blob/develop/t/destructive/peers_test.go#L62)) was testing false-positives on `shhext_post` calls, e.g: the network says we sent a message but we didn't.

As we're moving the test logic outside of the node, we won't have access to methods like [SubscribeEnvelopeEvents](https://github.com/status-im/status-go/blob/develop/t/destructive/peers_test.go#L95), so we won't be able to say if a message was expired before even being sent.

One possible solution is to create a new blocking endpoint on status-go like `shhext_postconfirm` so it waits until the message is really sent / timed out and provides a valid output.

**Comment by adriacidre** [comment]
Blocked by https://github.com/status-im/status-go/issues/1041
